stages:
  - checks
  - build
  - docker

variables:
  KANIKO_IMAGE: gcr.io/kaniko-project/executor:v1.23.2-debug

checks::backend:
  stage: checks
  image: maven:3.9.11-eclipse-temurin-25
  cache:
    key: maven-$CI_COMMIT_REF_SLUG
    paths:
      - .m2/repository
  script:
    - mvn -B -f backend/pom.xml spotless:check

checks::frontend:
  stage: checks
  image: ghcr.io/rafaelurben/node25-trixie-with-jdk25:latest
  cache:
    key: npm-$CI_COMMIT_REF_SLUG
    paths:
      - frontend/.npm
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npm run generate:openapi
    - npm run lint
    - npx tsc -b

build::backend:
  stage: build
  image: maven:3.9.11-eclipse-temurin-25
  cache:
    key: maven-$CI_COMMIT_REF_SLUG
    paths:
      - .m2/repository
  script:
    - mvn -B -f backend/pom.xml -DskipTests package
  artifacts:
    paths:
      - backend/target/backend-*.jar
    expire_in: 1 day

build::frontend:
  stage: build
  image: ghcr.io/rafaelurben/node25-trixie-with-jdk25:latest
  cache:
    key: npm-$CI_COMMIT_REF_SLUG
    paths:
      - frontend/.npm
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - frontend/dist
      - frontend/nginx.conf
    expire_in: 1 day

.docker::preset:
  stage: docker
  image:
    name: $KANIKO_IMAGE
    entrypoint: [ "" ]
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"'
      when: manual
      allow_failure: true
    - when: on_success
  script:
    - |
      mkdir -p /kaniko/.docker
      cat > /kaniko/.docker/config.json <<EOF
      {"auths":{"$CI_REGISTRY":{"username":"$CI_REGISTRY_USER","password":"$CI_REGISTRY_PASSWORD"}}}
      EOF
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        /kaniko/executor --context "$CI_PROJECT_DIR" --dockerfile "$CI_PROJECT_DIR/$FOLDER_NAME/Dockerfile" --destination "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHA" --destination "$CI_REGISTRY_IMAGE/$IMAGE_NAME:latest"
      else
        /kaniko/executor --context "$CI_PROJECT_DIR" --dockerfile "$CI_PROJECT_DIR/$FOLDER_NAME/Dockerfile" --destination "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHA"
      fi

docker::backend:
  extends: .docker::preset
  needs:
    - job: build::backend
      artifacts: true
  variables:
    IMAGE_NAME: sheetmusic-learner/sheetmusic-learner-backend
    FOLDER_NAME: backend

docker::frontend:
  extends: .docker::preset
  needs:
    - job: build::frontend
      artifacts: true
  variables:
    IMAGE_NAME: sheetmusic-learner/sheetmusic-learner-frontend
    FOLDER_NAME: frontend
