volumes:
  postgres-data:

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:18.2-trixie
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  # https://github.com/Soluto/oidc-server-mock
  oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:0.12.1
    ports:
      - "4011:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNET_SERVICES_OPTIONS_INLINE: |
        {
          "ForwardedHeadersOptions": {
            "ForwardedHeaders" : "All"
          }
        }
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      SERVER_CORS_ALLOWED_ORIGINS_INLINE: |
        [
          "http://localhost:5173"
        ]
      LOGIN_OPTIONS_INLINE: |
        {
          "AllowRememberLogin": false
        }
      LOGOUT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }
      API_SCOPES_INLINE: |
        [
          {
            "Name": "api",
            "DisplayName": "Backend API access",
            "UserClaims": [
              "name",
              "email",
              "picture"
            ]
          }
        ]
      API_RESOURCES_INLINE: |
        []
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"a0aa35b4-d9f8-4f08-98cb-476678ae5c13",
            "Username":"rafael",
            "Password":"rafael",
            "Claims": [
              {
                "Type": "name",
                "Value": "Rafael Urben",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "dev@rafaelurben.ch",
                "ValueType": "string"
              },
              {
                "Type": "picture",
                "Value": "https://gravatar.com/avatar/a6edbd223876f44c6794092ec50f41dc?s=128",
                "ValueType": "string"
              }
            ]
          },
          {
            "SubjectId":"d68a5dac-c084-4887-ae3b-2c3373ce1c56",
            "Username":"rick",
            "Password":"rick",
            "Claims": [
              {
                "Type": "name",
                "Value": "Rick Astley",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "rick.astley@tpto.ch",
                "ValueType": "string"
              },
              {
                "Type": "picture",
                "Value": "https://gravatar.com/avatar/a6edbd223876f44c6794092ec50f41da?s=128",
                "ValueType": "string"
              }
            ]
          },
          {
            "SubjectId":"92bebadf-92c2-462a-b5f0-6c693772d8ae",
            "Username":"bart",
            "Password":"bart",
            "Claims": [
              {
                "Type": "name",
                "Value": "Bart Simpson",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "bart.simpson@tpto.ch",
                "ValueType": "string"
              },
              {
                "Type": "picture",
                "Value": "https://gravatar.com/avatar/a6edbd223876f44c6794092ec50f41da?s=128",
                "ValueType": "string"
              }
            ]
          }
        ]
      CLIENTS_CONFIGURATION_INLINE: |
        [
          {
            "ClientId": "sheetmusic-learner",
            "ClientSecrets": ["test"],
            "Description": "Client for sheetmusic-learner",
            "AllowedGrantTypes": ["authorization_code"],
            "AllowAccessTokensViaBrowser": true,
            "RedirectUris": ["http://localhost:5173"],
            "PostLogoutRedirectUris": ["http://localhost:5173"],
            "AllowedScopes": ["openid", "profile", "email", "api"],
            "AlwaysIncludeUserClaimsInIdToken": true,
            "AlwaysSendClientClaims": true,
            "RequirePkce": true,
            "IdentityTokenLifetime": 3600,
            "AccessTokenLifetime": 3600,
            "RequireClientSecret": false
          }
        ]
