# Preset for Coolify
services:
  postgresdb:
    image: postgres:18.2-trixie
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sheetmusic_learner}
      POSTGRES_USER: ${SERVICE_USER_PG}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_64_PG}
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: registry.cloud.rafaelurben.ch/sheetmusic-learner-backend:latest
    restart: unless-stopped
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SERVICE_USER_PG}
      SPRING_DATASOURCE_PASSWORD: ${SERVICE_PASSWORD_64_PG}

      # Configure these in Coolify UI.
      APP_S3_ENDPOINT_OVERRIDE: ${APP_S3_ENDPOINT_OVERRIDE}
      APP_S3_PUBLIC_BASE_URL: ${APP_S3_PUBLIC_BASE_URL}
      APP_S3_ACCESS_KEY: ${APP_S3_ACCESS_KEY}
      APP_S3_SECRET_KEY: ${APP_S3_SECRET_KEY}
      APP_S3_BUCKET: ${APP_S3_BUCKET}

  frontend:
    image: registry.cloud.rafaelurben.ch/sheetmusic-learner-frontend:latest
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    environment:
      SERVICE_URL_FRONTEND: ${SERVICE_URL_FRONTEND}

volumes:
  postgres-data:
