# Preset for Coolify
services:
  postgresdb:
    image: postgres:18.2-trixie
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sheetmusic_learner}
      POSTGRES_USER: ${SERVICE_USER_PG}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_64_PG}
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: registry.cloud.rafaelurben.ch/sheetmusic-learner/sheetmusic-learner-backend:latest
    restart: unless-stopped
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SERVICE_USER_PG}
      SPRING_DATASOURCE_PASSWORD: ${SERVICE_PASSWORD_64_PG}

      # Configure these in Coolify UI.
      APP_S3_REGION: ${APP_S3_REGION}
      APP_S3_ENDPOINTOVERRIDE: ${APP_S3_ENDPOINTOVERRIDE}
      APP_S3_PUBLICBASEURL: ${APP_S3_PUBLICBASEURL}
      APP_S3_ACCESSKEY: ${APP_S3_ACCESSKEY}
      APP_S3_SECRETKEY: ${APP_S3_SECRETKEY}
      APP_S3_BUCKET: ${APP_S3_BUCKET}
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/8080'"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: registry.cloud.rafaelurben.ch/sheetmusic-learner/sheetmusic-learner-frontend:latest
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    environment:
      SERVICE_URL_FRONTEND: ${SERVICE_URL_FRONTEND}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
