spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres

app:
  oidc:
    client-id: sheetmusic-learner
    issuer: http://localhost:4011
    scope: openid profile email api
  s3:
    endpoint-override: http://localhost:9000
    public-base-url: http://localhost:9000/sheetmusic-learner-scores
    access-key: sheetmusic-access
    secret-key: sheetmusic-secret
    bucket: sheetmusic-learner-scores

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.messaging: DEBUG
    ch.rafaelurben: DEBUG
