spring.datasource:
  url: jdbc:postgresql://localhost:5433/postgres
  username: postgres
  password: postgres

app:
  oidc:
    client-id: sheetmusic-learner
    issuer: http://localhost:4011
    scope: openid profile email

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.messaging: DEBUG
    ch.rafaelurben: DEBUG
