spring.datasource:
  url: jdbc:postgresql://postgresdb:5433/postgres
  username: postgres
  password: postgres

app:
  oidc:
    client-id: sheetmusic-learner
    issuer: http://host.docker.internal:4011
    scope: openid profile email api
  s3:
    endpoint-override: http://minio:9000
    public-base-url: http://localhost:9000
    access-key: sheetmusic-access
    secret-key: sheetmusic-secret
    bucket: sheetmusic-learner-scores

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.messaging: DEBUG
    ch.rafaelurben: DEBUG
